#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 18 13:47:59 2021

@author: heiko
"""

from allensdk.core.brain_observatory_cache import BrainObservatoryCache
import allensdk.brain_observatory.natural_scenes as ns
import allensdk.brain_observatory.stimulus_info as stim_info
import numpy as np
import pandas as pd
import os
import pyrsa


boc = BrainObservatoryCache(manifest_file='boc/manifest.json')
nwb_filename = 'boc/ophys_experiment_data/%d.nwb'


def download(exp_id, folder='allen_data'):
    """ downloads a specific experiment and extracts the mean cell responses
    from the df/f traces for n frames after the exp_id"""
    if not os.path.isdir(folder):
        os.mkdir(folder)
    filename = os.path.join(folder, 'U_%d.npz' % exp_id)
    if not os.path.isfile(filename):
        exp_data = boc.get_ophys_experiment_data(exp_id)
        exp_ana = ns.NaturalScenes(exp_data)
        stim_table = exp_ana.stim_table
        stimulus = stim_table['frame']
        t_dff, dff = exp_data.get_dff_traces()
        U = np.empty((len(stim_table), exp_data.number_of_cells))
        for i in range(len(stim_table)):
            resp = dff[:, (stim_table['start'][i]+1):(stim_table['end'][i])]
            U[i] = np.mean(resp, 1)
        np.savez(filename, stimulus=stimulus, U=U)
        # remove file after U download to save space
        # os.remove(nwb_filename % exp_id)
    else:
        d_dict = np.load(filename)
        stimulus = d_dict['stimulus']
        U = d_dict['U']
    return U.shape


def download_all(folder='allen_data'):
    csv_file = folder + '.csv'
    if not os.path.isfile(csv_file):
        experiments = boc.get_ophys_experiments(
            stimuli=[stim_info.NATURAL_SCENES],
            cre_lines=['Cux2-CreERT2', 'Emx1-IRES-Cre', 'Slc17a7-IRES2-Cre'])
        exp_df = pd.DataFrame(experiments)
        exp_df.to_csv(csv_file)
    else:
        exp_df = pd.read_csv(csv_file)
    order = np.random.permutation(len(exp_df))
    exp_df['n_stim'] = np.nan
    exp_df['n_cell'] = np.nan
    for idx in order:
        n_stim, n_cell = download(exp_df['id'][idx], folder=folder)
        print('downloaded %d: %d' % (idx, exp_df['id'][idx]))
        exp_df.at[idx, 'n_stim'] = n_stim
        exp_df.at[idx, 'n_cell'] = n_cell
    if not os.path.isfile(csv_file):
        exp_df.to_csv(csv_file)


def resample(n_subj, n_stim, n_repeat, n_cell, folder='allen_data',
             targeted_structure='VISal'):
    """ gets a resampled dataset generated by sampling from the allen dataset

    Args:
    n_subj (int): number of mice
    n_stim (int): number of stimuli
    n_repeat (int): number of repeats
    n_cell (int): number of cells
    folder (str, folder), optional:
        the folder with the downloaded data. The default is 'allen_data'.

    targeted structures are:
        'VISal', 'VISam', 'VISl', 'VISp', 'VISpm', 'VISrl'

    Returns
    -------
    list of pyrsa.data.Dataset for the requested data, one dataset per subject

    """
    csv_file = folder + '.csv'
    exp_df = pd.read_csv(csv_file)
    exp_df = exp_df[exp_df.n_cell >= n_cell]
    right_tar_df = exp_df[exp_df['targeted_structure'] == targeted_structure]
    subs = np.unique(right_tar_df['donor_name'])
    subj_idx = subs[np.random.permutation(len(subs))[:n_subj]]
    stim_idx = np.random.permutation(118)[:n_stim]
    U_all = np.empty((n_subj, n_stim, n_repeat, n_cell))
    for i_subj, subj in enumerate(subj_idx):
        right_sub_df = right_tar_df[
            right_tar_df['donor_name'] == subj]
        if len(right_sub_df) == 1:
            exp_id = right_sub_df.iloc()[0]['id']
        else:
            k = np.random.randint(len(right_sub_df))
            exp_id = right_sub_df.iloc()[k]['id']
        dat = np.load('allen_data/U_%d.npz' % exp_id)
        U = dat['U']
        stimulus = dat['stimulus']
        for i_stim, stim in enumerate(stim_idx):
            U_stim = U[stimulus == stim]
            rep_idx = np.random.permutation(U_stim.shape[0])[:n_repeat]
            cell_idx = np.random.permutation(U_stim.shape[1])[:n_cell]
            U_all[i_subj, i_stim] = U_stim[rep_idx][:, cell_idx]
    U_pyrsa = U_all.transpose(0, 3, 1, 2).reshape(
        n_subj, n_cell, n_stim * n_repeat).transpose(0, 2, 1)
    stim = np.repeat(stim_idx, n_repeat)
    datasets = []
    for i_subj in range(n_subj):
        dataset = pyrsa.data.Dataset(
            U_pyrsa[i_subj],
            obs_descriptors={
                'stim': stim},
            descriptors={
                'subj': i_subj,
                'n_repeat': n_repeat,
                'n_stim': n_stim,
                'n_cell': n_cell,
                'targeted_structure': targeted_structure}
            )
        datasets.append(dataset)
    return datasets


def get_model_rdm(folder='allen_data', method='crossnobis', sim_type='cosine',
                  targeted_structure='VISal', min_cell=20):
    csv_file = folder + '.csv'
    exp_df = pd.read_csv(csv_file)
    exp_df = exp_df[exp_df.n_cell >= min_cell]
    right_tar_df = exp_df[exp_df['targeted_structure'] == targeted_structure]
    subs = np.unique(right_tar_df['donor_name'])
    datasets = []
    for i_subj, subj in enumerate(subs):
        right_sub_df = right_tar_df[
            right_tar_df['donor_name'] == subj]
        for i_exp, exp_row in right_sub_df.iterrows():
            exp_id = exp_row['id']
            dat = np.load('allen_data/U_%d.npz' % exp_id)
            U = dat['U']
            stimulus = dat['stimulus']
            dataset = pyrsa.data.Dataset(
                U,
                obs_descriptors={
                    'stim': stimulus},
                descriptors={
                    'subj': i_subj,
                    'targeted_structure': targeted_structure}
                )
            datasets.append(dataset)
    # we don't have a cv_descriptor here
    rdms = pyrsa.rdm.calc_rdm(datasets, method=method, descriptor='stim',
                              cv_descriptor=None)
    rdm = pyrsa.util.inference_util.pool_rdm(rdms)
    return rdm



if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--folder', type=str,
                        help='where should the allen data be?',
                        default='allen_data')
    parser.add_argument('action', help='what to do?', type=str,
                        choices=['download', 'nothing'],
                        default='nothing', nargs='?')
    args = parser.parse_args()
    if args.action == 'download':
        download_all(args.folder)
    else:
        print('No action selected, I am done!')
